### ISSUE TITLE
Do you have in mind to publish a new release?

### ISSUE THREAD

**Issue by insideth** [hypeJunction/hypeGallery#57] opened 2015-11-11 10:18 UTC
Images displaying is not working properly for me in Elgg 1.11

**Comment by hypeJunction** [comment] 2015-11-11 21:14
More info? Log entries? Working fine on my end.

**Comment by insideth** [comment] 2015-11-12 09:01
I have Elgg 1.11, hypeApps 4.3.3 and hypeGallery 3.1.0. Also tested with hypeDropzone 4.2.1.

Tested with all plugins disabled. PHP 5.5 with memory_limit: 256mb and post_max_size: 50mb . All plugins dependencies updated with composer.  

Problem seems be about thumbnails generation, this is the log when I upload an image:

```
2015/11/12 09:47:21 [error] 1189#0: *187 FastCGI sent in stderr: "PHP message: PHP WARNING: 2015-11-12 09:47:19 (CET): "finfo_file(icons/288topbar.jpg): failed to open stream: No such file or directory" in file /home/www/redup_triploader_com/htdocs/engine/classes/ElggFile.php (line 148)
PHP message: PHP WARNING: 2015-11-12 09:47:19 (CET): "mime_content_type(icons/288topbar.jpg): failed to open stream: No such file or directory" in file /home/www/redup_triploader_com/htdocs/engine/classes/ElggFile.php (line 154)
PHP message: PHP WARNING: 2015-11-12 09:47:19 (CET): "finfo_file(icons/288tiny.jpg): failed to open stream: No such file or directory" in file /home/www/redup_triploader_com/htdocs/engine/classes/ElggFile.php (line 148)
PHP message: PHP WARNING: 2015-11-12 09:47:19 (CET): "mime_content_type(icons/288tiny.jpg): failed to open stream: No such file or directory" in file /home/www/redup_triploader_com/htdocs/engine/classes/ElggFile.php (line 154)
PHP message: PHP WARNING: 2015-11-12 09:47:20 (CET): "finfo_file(icons/288small.jpg): failed to open stream: No such file or directory" in file /home/www/redup_triploader_com/htdocs/engine/classes/ElggFile.php (line 148)
PHP message: PHP WARNING: 2015-11-12 09:47:20 (CET): "mime_content_type(icons/288small.jpg): failed to open stream: No such file or directory" in file /home/www/redup_triploader_com/htdocs/engine/classes/ElggFile.php (line 154)
PHP message: PHP WARNING: 2015-11-12 09:47:20 (CET): "finfo_file(icons/288medium.jpg): failed to open stream: No such file or directory" in file /home/www/redup_triploader_com/htdocs/engine/classes/ElggFile.php (line 148)
PHP message: PHP WARNING: 2015-11-12 09:47:20 (CET): "mime_content_type(icons/288medium.jpg): failed to open stream: No such file or directory" in file /home/www/redup_triploader_com/htdocs/engine/classes/ElggFile.php (line 154)
PHP message: PHP WARNING: 2015-11-12 09:47:20 (CET): "finfo_file(icons/288large.jpg): failed to open stream: No such file or directory" in file /home/www/redup_triploader_com/htdocs/e
2015/11/12 09:47:21 [error] 1189#0: *187 FastCGI sent in stderr: "ome/www/redup_triploader_com/htdocs/engine/classes/ElggFile.php (line 148)
PHP message: PHP WARNING: 2015-11-12 09:47:21 (CET): "mime_content_type(icons/2890.png): failed to open stream: No such file or directory" in file /home/www/redup_triploader_com/htdocs/engine/classes/ElggFile.php (line 154)
PHP message: PHP WARNING: 2015-11-12 09:47:21 (CET): "finfo_file(icons/289325x200.png): failed to open stream: No such file or directory" in file /home/www/redup_triploader_com/htdocs/engine/classes/ElggFile.php (line 148)
PHP message: PHP WARNING: 2015-11-12 09:47:21 (CET): "mime_content_type(icons/289325x200.png): failed to open stream: No such file or directory" in file /home/www/redup_triploader_com/htdocs/engine/classes/ElggFile.php (line 154)
PHP message: PHP WARNING: 2015-11-12 09:47:21 (CET): "finfo_file(icons/289taggable.png): failed to open stream: No such file or directory" in file /home/www/redup_triploader_com/htdocs/engine/classes/ElggFile.php (line 148)
PHP message: PHP WARNING: 2015-11-12 09:47:21 (CET): "mime_content_type(icons/289taggable.png): failed to open stream: No such file or directory" in file /home/www/redup_triploader_com/htdocs/engine/classes/ElggFile.php (line 154)" while reading response header from upstream, client: 192.168.56.101, server: local.redup.triploader.com, request: "POST /action/edit/object/hjalbum HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "local.redup.triploader.com", referrer: "http://local.redup.triploader.com/gallery/create/album/106"

```

So images are displayed wrong (for example cover image):

![image](https://cloud.githubusercontent.com/assets/6679837/11114245/863b85a2-8923-11e5-965a-7717f87d60c2.png)

**Comment by hypeJunction** [comment] 2015-11-12 10:02
It's a bug in core, which has been fixed in 1.12. The problem is that `ElggFile::detectMimeType()` uses the wrong file path, and can't detect the correct mime.

**Comment by insideth** [comment] 2015-11-12 19:09
I´ve just upgraded to Elgg 1.12.4 (and PHP 5.6) and PHP WARNINGs disapeared, but thumbnails still are wrong generated.

For example cover photo has the right url (../gallery/icon/311/800x200), but as you can see on the bottom capture a different size is displayed.

This is the log:

```
2015/11/12 20:02:21 [error] 1172#1172: *1223 FastCGI sent in stderr: "PHP message: PHP NOTICE: 2015-11-12 20:02:20 (CET): "Undefined variable: entity" in file /home/www/redup_triploader_com/htdocs/mod/hypeGallery/actions/edit/object/hjalbum.php (line 31)
PHP message: PHP NOTICE: 2015-11-12 20:02:20 (CET): "Trying to get property of non-object" in file /home/www/redup_triploader_com/htdocs/mod/hypeGallery/actions/edit/object/hjalbum.php (line 31)
PHP message: PHP NOTICE: 2015-11-12 20:02:21 (CET): "Undefined variable: filename" in file /home/www/redup_triploader_com/htdocs/mod/hypeApps/classes/hypeJunction/Services/IconFactory.php (line 211)
PHP message: PHP NOTICE: 2015-11-12 20:02:21 (CET): "Undefined variable: filename" in file /home/www/redup_triploader_com/htdocs/mod/hypeApps/classes/hypeJunction/Services/IconFactory.php (line 211)
PHP message: PHP NOTICE: 2015-11-12 20:02:21 (CET): "Undefined variable: filename" in file /home/www/redup_triploader_com/htdocs/mod/hypeApps/classes/hypeJunction/Services/IconFactory.php (line 211)
PHP message: PHP NOTICE: 2015-11-12 20:02:21 (CET): "Undefined variable: filename" in file /home/www/redup_triploader_com/htdocs/mod/hypeApps/classes/hypeJunction/Services/IconFactory.php (line 211)
PHP message: PHP NOTICE: 2015-11-12 20:02:21 (CET): "Undefined variable: filename" in file /home/www/redup_triploader_com/htdocs/mod/hypeApps/classes/hypeJunction/Services/IconFactory.php (line 211)
PHP message: PHP NOTICE: 2015-11-12 20:02:21 (CET): "Undefined variable: filename" in file /home/www/redup_triploader_com/htdocs/mod/hypeApps/classes/hypeJunction/Services/IconFactory.php (line 211)
PHP message: PHP NOTICE: 2015-11-12 20:02:21 (CET): "Undefined variable: filename" in file /home/www/redup_triploader_com/htdocs/mod/hypeApps/classes/hypeJunction/Services/IconFactory.php (line 211)
PHP message: PHP NOTICE: 2015-11-12 20:02:21 (CET): "Undefined variable: filename" in file /home/www/redup_triploader_com/htdocs/mod/hypeApps/classes/hypeJunction/Services/IconFactory.php (line 211)
PHP m
2015/11/12 20:02:21 [error] 1172#1172: *1219 FastCGI sent in stderr: "PHP message: PHP NOTICE: 2015-11-12 20:02:21 (CET): "Undefined variable: cover_image" in file /home/www/redup_triploader_com/htdocs/mod/hypeGallery/classes/hypeJunction/Gallery/hjAlbum.php (line 90)
PHP message: PHP NOTICE: 2015-11-12 20:02:21 (CET): "Undefined variable: info" in file /home/www/redup_triploader_com/htdocs/mod/hypeGallery/views/default/object/hjalbum/gallery.php (line 56)
PHP message: PHP NOTICE: 2015-11-12 20:02:21 (CET): "Undefined variable: requested_h" in file /home/www/redup_triploader_com/htdocs/mod/hypeGallery/views/default/icon/object/hjalbumimage.php (line 35)
PHP message: PHP NOTICE: 2015-11-12 20:02:21 (CET): "Undefined variable: requested_h" in file /home/www/redup_triploader_com/htdocs/mod/hypeGallery/views/default/icon/object/hjalbumimage.php (line 40)
PHP message: PHP NOTICE: 2015-11-12 20:02:21 (CET): "Undefined variable: size" in file /home/www/redup_triploader_com/htdocs/mod/hypeGallery/views/default/forms/edit/object/hjalbumimage.php (line 11)
PHP message: PHP NOTICE: 2015-11-12 20:02:21 (CET): "Undefined offset: 1" in file /home/www/redup_triploader_com/htdocs/mod/hypeGallery/views/default/icon/object/hjalbumimage.php (line 18)
PHP message: PHP NOTICE: 2015-11-12 20:02:21 (CET): "Undefined variable: info" in file /home/www/redup_triploader_com/htdocs/mod/hypeGallery/views/default/forms/edit/object/hjalbumimage.php (line 27)
PHP message: PHP NOTICE: 2015-11-12 20:02:21 (CET): "Undefined variable: cover_image" in file /home/www/redup_triploader_com/htdocs/mod/hypeGallery/classes/hypeJunction/Gallery/hjAlbum.php (line 90)" while reading response header from upstream, client: 192.168.56.102, server: local.redup.triploader.com, request: "GET /gallery/manage/310 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "local.redup.triploader.com", referrer: "http://local.redup.triploader.com/gallery/create/album/214"
2015/11/12 20:02:22 [error] 1172#1172: *1219 FastCGI sent in stderr: "PHP message: PHP NOTICE: 2015-11-12 20:02:22 (CET): "Undefined variable: filehandler" in file /home/www/redup_triploader_com/htdocs/mod/hypeGallery/pages/gallery/icon/icon.php (line 29)
PHP message: PHP NOTICE: 2015-11-12 20:02:22 (CET): "Trying to get property of non-object" in file /home/www/redup_triploader_com/htdocs/mod/hypeGallery/pages/gallery/icon/icon.php (line 29)
PHP message: PHP NOTICE: 2015-11-12 20:02:22 (CET): "Undefined variable: mime" in file /home/www/redup_triploader_com/htdocs/mod/hypeGallery/pages/gallery/icon/icon.php (line 128)" while reading response header from upstream, client: 192.168.56.102, server: local.redup.triploader.com, request: "GET /gallery/icon/311/800x200 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "local.redup.triploader.com", referrer: "http://local.redup.triploader.com/gallery/manage/310"
2015/11/12 20:02:22 [error] 1172#1172: *1223 FastCGI sent in stderr: "PHP message: PHP NOTICE: 2015-11-12 20:02:22 (CET): "Undefined variable: filehandler" in file /home/www/redup_triploader_com/htdocs/mod/hypeGallery/pages/gallery/icon/icon.php (line 29)
PHP message: PHP NOTICE: 2015-11-12 20:02:22 (CET): "Trying to get property of non-object" in file /home/www/redup_triploader_com/htdocs/mod/hypeGallery/pages/gallery/icon/icon.php (line 29)
PHP message: PHP NOTICE: 2015-11-12 20:02:22 (CET): "Undefined variable: mime" in file /home/www/redup_triploader_com/htdocs/mod/hypeGallery/pages/gallery/icon/icon.php (line 128)" while reading response header from upstream, client: 192.168.56.102, server: local.redup.triploader.com, request: "GET /gallery/icon/311/325x200 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "local.redup.triploader.com", referrer: "http://local.redup.triploader.com/gallery/manage/310"
2015/11/12 20:02:22 [error] 1172#1172: *1226 FastCGI sent in stderr: "PHP message: PHP NOTICE: 2015-11-12 20:02:22 (CET): "Undefined variable: filehandler" in file /home/www/redup_triploader_com/htdocs/mod/hypeGallery/pages/gallery/icon/icon.php (line 29)
PHP message: PHP NOTICE: 2015-11-12 20:02:22 (CET): "Trying to get property of non-object" in file /home/www/redup_triploader_com/htdocs/mod/hypeGallery/pages/gallery/icon/icon.php (line 29)
PHP message: PHP NOTICE: 2015-11-12 20:02:22 (CET): "Undefined variable: mime" in file /home/www/redup_triploader_com/htdocs/mod/hypeGallery/pages/gallery/icon/icon.php (line 128)" while reading response header from upstream, client: 192.168.56.102, server: local.redup.triploader.com, request: "GET /gallery/icon/311/small HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "local.redup.triploader.com", referrer: "http://local.redup.triploader.com/gallery/manage/310"
``` 
![captura](https://cloud.githubusercontent.com/assets/6679837/11128303/425d630e-8979-11e5-9daa-2ef26fc11a37.PNG)

**Comment by insideth** [comment] 2015-11-13 10:42
Ismayil if it helps, this issue appeared from Elgg 1.10 (with 1.9 it worked fine)

**Comment by hypeJunction** [comment] 2015-11-16 08:26
Just started seeing on a site I am working on. I will dig into it soon.

**Comment by insideth** [comment] 2015-11-16 11:32
Ok Ismayil thank you, I wait for your comments.

**Comment by insideth** [comment] 2015-11-25 08:38
Some more logs from other installations about this issue (Elgg 1.12)

hypeGallery:

```
2015/11/25 09:28:24 [error] 3747#3747: *5235 FastCGI sent in stderr: "PHP message: PHP WARNING: 2015-11-25 09:28:23 (CET): "Missing argument 3 for hypeJunction\Services\IconFactory::getIconFile(), called in /home/www/demo_cloudaws_es/htdocs/mod/hypeApps/classes/hypeJunction/Services/IconFactory.php on line 81 and defined" in file /home/www/demo_cloudaws_es/htdocs/mod/hypeApps/classes/hypeJunction/Services/IconFactory.php (line 236)
PHP message: PHP WARNING: 2015-11-25 09:28:23 (CET): "Missing argument 3 for hypeJunction\Services\IconFactory::getIconFile(), called in /home/www/demo_cloudaws_es/htdocs/mod/hypeApps/classes/hypeJunction/Services/IconFactory.php on line 81 and defined" in file /home/www/demo_cloudaws_es/htdocs/mod/hypeApps/classes/hypeJunction/Services/IconFactory.php (line 236)
PHP message: PHP WARNING: 2015-11-25 09:28:23 (CET): "Missing argument 3 for hypeJunction\Services\IconFactory::getIconFile(), called in /home/www/demo_cloudaws_es/htdocs/mod/hypeApps/classes/hypeJunction/Services/IconFactory.php on line 81 and defined" in file /home/www/demo_cloudaws_es/htdocs/mod/hypeApps/classes/hypeJunction/Services/IconFactory.php (line 236)
PHP message: PHP WARNING: 2015-11-25 09:28:23 (CET): "Missing argument 3 for hypeJunction\Services\IconFactory::getIconFile(), called in /home/www/demo_cloudaws_es/htdocs/mod/hypeApps/classes/hypeJunction/Services/IconFactory.php on line 81 and defined" in file /home/www/demo_cloudaws_es/htdocs/mod/hypeApps/classes/hypeJunction/Services/IconFactory.php (line 236)
PHP message: PHP WARNING: 2015-11-25 09:28:23 (CET): "Missing argument 3 for hypeJunction\Services\IconFactory::getIconFile(), called in /home/www/demo_cloudaws_es/htdocs/mod/hypeApps/classes/hypeJunction/Services/IconFactory.php on line 81 and defined" in file /home/www/demo_cloudaws_es/htdocs/mod/hypeApps/classes/hypeJunction/Services/IconFactory.php (line 236)

```

hypeScraper

```
PHP message: PHP WARNING: 2015-11-25 09:28:23 (CET): "Missing argument 3 for hypeJunction\Services\IconFactory::getIconFile(), called in /home/www/
2015/11/25 09:31:50 [error] 3745#3745: *5271 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'hypeJunction\Servers\IconServer' not found in /home/www/demo_cloudaws_es/htdocs/mod/hypeApps/servers/icon.php on line 4" while reading response header from upstream, client: 192.168.56.101, server: local.demo.cloudaws.es, request: "GET /mod/hypeApps/servers/icon.php?q=YTo2OntzOjM6InVpZCI7czozMjoiM2VmMWRkMWVkNzkxOTdkYmIyMWQyZWJiYjg3YmExYjAiO3M6NDoicGF0aCI7czo1OToic2NyYXBlcl9jYWNoZS90aHVtYnMvM2VmMWRkMWVkNzkxOTdkYmIyMWQyZWJiYjg3YmExYjAuMS5qcGciO3M6MToiZCI7aToxO3M6MzoiZHRzIjtpOjE0MzIyMDM5NjI7czoyOiJ0cyI7aToxNDQ4NDM5MDkwO3M6MzoibWFjIjtzOjY0OiI4NDMzMWRkZTgyZjJiOGVlNGQ3N2E1MGYwM2Q5ZDlkNmU1NTMyYjJiNmVmYjNiOTQxYTM5MDI4MTg1YmNmOTMwIjt9 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "local.demo.cloudaws.es", referrer: "http://local.demo.cloudaws.es/profile/jm
```

**Closed** 2016-01-06 12:27 UTC
